export default {
  button: {
    position: 'absolute',
    right: 42,
    top: 0,
    transform: 'translateY(50%)',
  },
  item: {
    position: 'relative',
    margin: 0,
    padding: 0,
    width: 306,
    '&:first-child': {
      marginTop: 63,
    },
    '&:before': {
      content: '" " ',
      position: 'absolute',
      width: 1,
      height: 44,
      top: 0,
      left: 1,
      background: '#016BFC',
      zIndex: 10,
    },
  },
  itemHide: {
    position: 'relative',
    margin: 0,
    padding: 0,
    width: 25,
    zIndex: 13,
    '&:first-child': {
      marginTop: 63,
    },
    '& > a': {
      position: 'relative',
      backgroundColor: 'transparent',
      paddingLeft: 15,
      '& > span': {
        display: 'none',
      },
    },
    '&:hover': {
      width: 326,
      '& > ul': {
        position: 'absolute',
        display: 'block',
        paddingBottom: 10,
        top: 29,
        left: 50,
        width: 276,
        zIndex: 3,
        backgroundColor: '#3D5677',
        '& > div': {
          display: 'flex',
          justifyContent: 'center',
        },
      },
      '& > a': {
        backgroundColor: '#374C66',
        '& > span': {
          display: 'inline',
        },
      },
    },
  },
  link: {
    position: 'relative',
    padding: 0,
    display: 'block',
    color: '#fff',
    backgroundColor: '#374C66',
    height: 44,
    lineHeight: '44px',
    fontFamily: "'Roboto', sans-serif",
    fontSize: 16,
    textDecoration: 'none',
    '&:hover': {
      outline: 'none',
      textDecoration: 'none',
      color: '#fff',
    },
  },
  arrow: {
    top: 0,
    marginTop: 16,
    right: 18,
    width: 7,
    height: 7,
    borderTop: '1px solid #fff',
    position: 'absolute',
    borderLeft: '1px solid #fff',
  },
  icon: {
    position: 'absolute',
    width: 37,
    textAlign: 'center',
  },
  more: {
    position: 'absolute',
    height: 3,
    right: 40,
    transform: 'translateY(-50%)',
  },
  dot: {
    display: 'inline-block',
    backgroundColor: '#fff',
    width: 3,
    height: 3,
    marginRight: 4,
    border: '1px solid #FFFFFF',
    borderRadius: '50%',
  },
  treeMenu: {
    display: 'none',
    listStyle: 'none',
    padding: 0,
    margin: '15px 0 25px 0',
    fontFamily: "'Roboto', sans-serif",
    fontSize: 14,
    color: '#fff',
  },
  treeMenuActive: {
    display: 'block',
  },
  circleBtn: {
    display: 'inline-block',
    width: 22,
    height: 22,
    textAlign: 'center',    
    verticalAlign: 'middle',
    borderRadius: '50%',
    color: '#fff',
    background: '#016BFC',
  },
}