export default {
  sidebarCollapse: {
    transform: 'translate(-306px, 0)',
  },
  mainHeader: {
    position: 'fixed',
    width: '100%',
    display: 'flex',
    background: '#fff',
    fontFamily: "'Roboto', sans-serif",
    zIndex: 1030,
  },
  navBar: {
    position: 'relative',
    height: 60,
  },
  img: {
    height: 59,
    width: 59,
    verticalAlign: 'top',
  },
  imgMini: {
    width: 45,
    height: 'auto',
  },
  menu: {
    position :'relative',
    display: 'inline-block',
    width: 60,
    height: 60,
    lineHeight: '60px',
    textAlign: 'center',
    background: '#016BFC',
    boxShadow: '0px 0px 10px rgba(0, 0, 0, 0.05)',
  },
  lines: {
    position: 'absolute',
    left: 17,
    top: 19,
    width: 21,
    height: 16,    
    borderTop: 'solid 1px #fff',
    borderBottom: 'solid 1px #fff',
  },
  lines1: {
    position: 'absolute',
    left: 17,
    top: 26,
    width: 27,
    height: 16,    
    borderTop: 'solid 1px #fff',
    borderBottom: 'solid 1px #fff',
  },
  dateItem: {
    display: 'inline-block',
    width: 152,
    marginRight: 20,
    textAlign: 'left',
    verticalAlign: 'top',
    color: '#ADB2BA',
    fontSize: 16,
    lineHeight: '60px',
    cursor: 'pointer',
  },
  calendarIcon: {
    display: 'inline-block',
    marginRight: 20,
    marginLeft: 15,
    verticalAlign: 'top',
    lineHeight: '60px',
  },
  peopleBtn: {
    display: 'inline-block',
    width: 36,
    height: 36,
    marginTop: 12,
    marginLeft: 10,
    background: '#016BFC',
    borderRadius: 3,
    textAlign: 'center',
    verticalAlign: 'top',
    lineHeight: '35px',
  }
}